

module.exports = [
 

 
  "t-shirt for men",
  "t-shirt for women",
  "hoodie for men",
  "hoodie for women",
  "jeans",
  "bag",
  "sunglass",
  "cycle",
  "bottle",
  "cake",
  "electronics",
  "smartphones",
  "laptops",
  "headphones",
  "watch",
  "shoes",
  "slippers",
  "books",
  "stationery",
  "home decor",
  "kitchen appliances",
  "fitness equipment",
  "toys",
  "skincare",
  "haircare",
  "groceries",
  "furniture",
  "mobile accessories",
  "camera",
  "gaming console",
  "sportswear",
  "makeup",
  "baby products",
  "pet supplies",
  "cleaning essentials",
  "school bags",
  "notebooks",
  "travel accessories",
  "lighting",
  "winter wear",
  "summer wear",
  "indian wear",
  "western wear",
  "ethnic wear",
  "bathroom essentials",
  "plant pots",
  "wall art",
  "phone cases",
  "power banks",
  "smartwatches",
  "bluetooth speakers",
  "tablets",
  "printers",
  "monitors",
  "tv",
  "set top box",
  "microwave",
  "refrigerator",
  "washing machine",
  "water bottles",
  "lunch boxes",
  "pens",
  "pencils",
  "drawing books",
  "color sets",
  "yoga mats",
  "dumbbells",
  "treadmills",
  "bicycles",
  "helmets",
  "raincoats",
  "jackets",
  "sweaters",
  "sandals",
  "heels",
  "flip flops",
  "formal shoes",
  "casual shoes",

  
  "wallets",
  "belts",
  "caps",
  "socks",
  "innerwear",
  "thermals",
  "maternity wear",
  "baby clothing",
  "baby toys",
  "kids fashion",
  "party wear",
  "gift items",
  "art supplies",
  "diaries",
  "planners",
  "mirrors",
  "curtains",
  "bedsheets",
  "pillows",
  "mats",
  "carpets",
  "room fresheners",
  "candles",
  "lamps",
  "clocks",
  "extension cords",
  "chargers",
  "tripods",
  "dslr cameras",
  "gaming mouse",
  "gaming keyboards",
  "vr headset",
  "drone cameras",
  "action cameras",
  "projectors"


  
];
